### ISSUE TITLE
Holographic remoting with OpenXR and HandTrackerEXT problems

### ISSUE THREAD

**Issue by ajinchv** [microsoft/MixedReality-HolographicRemoting-Samples#45] opened 2021-09-22 12:44 UTC
I am writing a C++ application using OpenXR and holographic remoting and I have issues using the XrHandTrackerEXT extension. The runtime reports that the extension is supported, the system properties report that the hand tracking is supported, and the code runs without any OpenXR errors. However I always get zero results from xrLocateHandJointsEXT function.

**Comment by FlorianBagarMicrosoft** [comment] 2021-09-23 11:27
Hi ajinchv,
what version of Holograhic Remoting are you using? With version 2.6.0 everything is working fine with our internal test app.
Also, have you tried running your remote app directly on HoloLens 2 using the native OpenXR runtime from the OS? Does the issue reproduce there as well?

**Comment by ajinchv** [comment] 2021-09-23 14:13
I was using version 2.4.1. Unfortunately it is not easy to run it natively on the device, since my implementation is part of a larger program, and its not easy to compile it for ARM64. I will attempt to use 2.6.x.

**Comment by maapp** [comment] 2022-07-18 09:05
Closing for now due to no updates. Let us know if you still need help.

**Closed by maapp** 2022-07-18 09:05 UTC
