### ISSUE TITLE
connect question

### ISSUE THREAD

**Issue by yinalger** [microsoft/MixedReality-HolographicRemoting-Samples#67] opened 2022-08-27 07:22 UTC
**Describe the bug**
      Can not connect the remote player which retrun Disconnected with reason 12(TransportConnectionFailed) and Holographic Remoting: Disconnected - Reason: 12(XR_REMOTING_DISCONNECT_REASON_TRANSPORT_CONNECTION_FAILED_MSFT)
      By the way I built the .sln in remote/uwp which can connect the player in holoens2.The another one which in remote/desktop can not.What is the difference between them.

**Remote side (your Windows PC):**
 - OS version: 22000.856
 - Are you using an engine (Unity/Unreal), if yes - which one and which version: [Unity 2022.1.1f1c1]
 - Are you using OpenXR or Windows Holographic (or the respective plugins for your engine)
 - Are you using your own render engine? If so - what version of the remoting SDK are you using? [2.8.0]
 - Graphics card(s) / graphics driver version: [nVidia RTX 3060 laptop with driver version 512.95, AMD Radeon(TM) Graphics 30.0.13002.1001]

**Comment by yinalger** [comment] 2022-09-07 01:11
@Hanaae-MSFT 
Thanks for the replay.I will try when I have free time.I tried the same project on anthor computer and successed.
I saw that h265 uses nvdia graphics card, but my CPU is AMD. It has amdh265 and does not support h265.Is this the possible cause of the problem?
As you might think, I tried to use playmoderemoting in unity, but it didn't work for the same reason.
When I searched the results, I found the OpenXR-Unity-MixedReality-Samples, which included appremoting. It works. They don't have much difference. The problem with uinty may be that I have not configured the correct environment.
You can close the problem.I solved my problem.And I will send the trace.etl quickly.
And the last,thanks for you help.

**Comment by Hanaae-MSFT** [comment] 2022-09-07 08:29
Thanks for the response. For machines, where there is more the one GPU, the selection of the correct GPU device could be a bit tricky. In your system, if I understood correctly, there are 2 GPUs, the dedicated Nvidia RTX 3060 and the integrated AMD Radeon one. However, it shouldn't be an issue which GPU is selected/enabled as long as the GPU supports H265 and you have the [HEVC video extensions](https://apps.microsoft.com/store/detail/hevc-video-extensions-from-device-manufacturer/9N4WGH0Z6VHQ?hl=en-us&gl=us) installed on your machine . 
Unfortunately, I would need more information to interpret what is exactly going on.
So, you are welcome any time to send me an etl trace to investigate it further and for now, I will close the issue since the problem is resolved.

**Closed** 2022-09-07 08:46 UTC
