### ISSUE TITLE
Audio is deformed when remoting audio from Windows and having headphones paired to the HoloLens 2

### ISSUE THREAD

**Issue by ikto-art** [microsoft/MixedReality-HolographicRemoting-Samples#76] opened 2023-01-14 14:10 UTC
**Describe the bug**
When using Remoting (both audio and video) with the default Remoting Player in the headset, the audio is severely deformed and lags with pauses and ticks, and the pitch is below normal like the sound was slowed down. This happens only when the HoloLens 2 is paired with Bluetooth headphones. With the HoloLens 2 integrated speakers or when the PC itself is paired to the headphones, the audio is normal.

**To Reproduce**
1. Launch remoting player on the HoloLens
2. Connect from a basic OpenXR remoting Unity project
3. Play audio either from the Unity player or Windows with Bluetooth headphones paired to the HoloLens 2

**Remote side (your Windows PC):**
 - OS version: tested on Windows 10 and 11
 - Are you using an engine (Unity/Unreal), if yes - which one and which version: Unity 2020.3.42f1
 - OpenXR 1.6.0 unity package
 - Graphics card(s) / graphics driver version: RTX 2070 driver 526.98
 - Unity audio engine: FMOD with FMOD Studio
 - Unity platform: UWP
 - Tested both in Editor mode and with a built Player

**Player side (e.g. your HoloLens 2)**
 - Windows version	20348.1531.arm64fre.fe_release_svc_sydney_rel_prod.221204-1412
 - OpenXR runtime version 112.2211.2002.0
 - Remoting player from the store, 2.8.1

I tested with 2 different headphones, I also tested that the pitch was below normal when playing sounds from Windows directly.

**Comment by Hanaae-MSFT** [comment] 2023-01-19 08:50
Hey ikto-art, we will look into it and get back to you. Thanks!

**Comment by ikto-art** [comment] 2023-02-23 19:35
Hi Hanaae, do you have any news on this?
I saw on the changelog that now it is possible to choose the audio source for Remoting but I don't know how to do that and the 2.9.0.0 version is currently unusable due to the most recent issue. (#81)
Thank you.

**Comment by ikto-art** [comment] 2023-03-22 06:49
Hello,

Still no solution after trying to change the sample rate of the Windows 11 audio device that is streaming the audio (32kHz, 44.1, 48) to the HoloLens and fiddling with FMOD sample rate settings. Whether it is on the official Remoting app or a compiled one from this sample we still have the same issue with 3 different Bluetooth headphones (Sennheiser, JBL, OpenRun Shokz).

There seems to be no setting to change the sample rate of the audio device on the HoloLens 2. Can it be done programmatically in the sample app?

Thanks.

**Comment by Hanaae-MSFT** [comment] 2023-03-23 16:54
Hello,
Sorry for the delayed response. As for the initial bug, unfortunately, I was not able to fully reproduce it on my side. Regarding choosing the audio source for Remoting with Unity, we spoke to the team responsible for the unity plugin and they are aware of it. However, we can't really confirm a release date that exposes this option in the plugin.
As for the sample rate of the audio device, we don't expose it via the Remoting API, so it can not be done in the SampleRemote app.

**Comment by ikto-art** [comment] 2023-03-24 07:40
Hi,

Unfortunately it seems to be more on the HoloLens side than the PC side so I don't know if choosing the audio source will fix this issue.
Can you please tell me more about the configuration you tested? Build or Editor, versions of Unity, packages, runtimes, Windows 11 or 10, etc.
If I can reproduce your setup, maybe I can fix the issue on my side.

Thank you very much

**Comment by simonrobl** [comment] 2023-12-20 12:36
Hi @ikto-art, since there hasn't been activity on this issue in some time I'll be closing it. If you are still encountering this issue feel free to reopen it :)

**Closed by simonrobl** 2023-12-20 12:36 UTC
